name: Android CI

on:
  push:
    paths:
      - '**.kt'
      - '**.xml'
      - '**.gradle'
      - '**.properties'
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: chmod 777 gradlew | ./gradlew assembleDebug